### ISSUE TITLE
add frontend button

### ISSUE THREAD

**Issue by SukeshAnchan** [SukeshAnchan/cognixia#2]
Please add frontend login button to our existing web page

**Comment by SukeshAnchan** [comment]
issue hasn't fixed yet. could you please look into it

**Comment by SukeshAnchan** [comment]
looks good. closing the issue.

**Comment by SukeshAnchan** [comment]
closing the ssue

**Comment by SukeshAnchan** [comment]
The old fix provided by the developer has an issue associated. need a emergency fix

**Comment by SukeshAnchan** [comment]
@DavidDStacey Hello David please provide a fix

**Comment by DavidDStacey** [comment]
fix issue #2

**Comment by SukeshAnchan** [comment]
Looks good David. Thank you!
